### ISSUE TITLE
how to change color of html tags?

### ISSUE THREAD

**Issue by jrafaaael** [rmehri01/onenord.nvim#8]

**Comment by rmehri01** [comment]
Hi, please refer to the configuration docs for how to override a highlight group: https://github.com/rmehri01/onenord.nvim#configuration.

If you are using tree sitter, then the group you are looking to override is `TSTagDelimiter = { fg = onenord.dark_blue }`.

**Comment by jrafaaael** [comment]
@rmehri01 not working for me...

`.config/nvim/lua/plugins/onenord.lua`:
```lua
local colors = require("onenord.colors")

require("onenord").setup({
  borders = true, -- Split window borders
  italics = {
    comments = false, -- Italic comments
    strings = false, -- Italic strings
    keywords = false, -- Italic keywords
    functions = false, -- Italic functions
    variables = false, -- Italic variables
  },
  disable = {
    background = false, -- Disable setting the background color
    cursorline = false, -- Disable the cursorline
    eob_lines = true, -- Hide the end-of-buffer lines
  },
  custom_highlights = {
    TSTagDelimiter = { fg = colors.orange }
  }, -- Overwrite default highlight groups
})
```
`.config/nvim/lua/plugins/init.lua`:
```lua
require('plugins.plugins')
require("plugins.onenord")
```

![Screenshot at 2021-11-08 14-49-08](https://user-images.githubusercontent.com/70046023/140800111-7b77d8b3-0d03-4ced-b56d-0b915c98ea28.png)

As you can see, the keyword `function` and the HTML tags remain the same as the default values
The file `onenord.lua` is required in `init.lua`

**Comment by rmehri01** [comment]
That's strange since that block you posted above seems to work for me. 

If none of the options are working, it may be a problem with your configuration. Are other plugins configured in this same way working as expected?

**Comment by jrafaaael** [comment]
@rmehri01 yes. The rest of the plugins work normally

**Comment by rmehri01** [comment]
Hmm okay, I've been trying to reproduce this but I can't really get it. Do you have a small complete config where this issue happens so that I could try it?

Here are the examples I tried.

Before:

```vim
call plug#begin('~/.config/nvim/autoload/plugged')
    Plug 'rmehri01/onenord.nvim', { 'branch': 'main' }
        " Better Syntax Support
    Plug 'sheerun/vim-polyglot'
    " File Explorer
    Plug 'scrooloose/NERDTree'
    " Auto pairs for '(' '[' '{'
    Plug 'jiangmiao/auto-pairs'
call plug#end()

lua << EOF
local colors = require("onenord.colors")

require("onenord").setup({
  borders = true, -- Split window borders
  italics = {
    comments = true, -- Italic comments
    strings = true, -- Italic strings
    keywords = true, -- Italic keywords
    functions = true, -- Italic functions
    variables = true, -- Italic variables
  },
  disable = {
    background = false, -- Disable setting the background color
    cursorline = false, -- Disable the cursorline
    eob_lines = true, -- Hide the end-of-buffer lines
  },
  custom_highlights = {
  }, -- Overwrite default highlight groups
})
EOF

colorscheme onenord
```
<img width="1542" alt="Screen Shot 2021-11-08 at 3 51 54 PM" src="https://user-images.githubusercontent.com/52933714/140836500-d4c6c51a-c31c-4acc-b03a-082a41ab1417.png">

After:
```vim
call plug#begin('~/.config/nvim/autoload/plugged')
    Plug 'rmehri01/onenord.nvim', { 'branch': 'main' }
        " Better Syntax Support
    Plug 'sheerun/vim-polyglot'
    " File Explorer
    Plug 'scrooloose/NERDTree'
    " Auto pairs for '(' '[' '{'
    Plug 'jiangmiao/auto-pairs'
call plug#end()

lua << EOF
local colors = require("onenord.colors")

require("onenord").setup({
  borders = true, -- Split window borders
  italics = {
    comments = true, -- Italic comments
    strings = true, -- Italic strings
    keywords = true, -- Italic keywords
    functions = true, -- Italic functions
    variables = true, -- Italic variables
  },
  disable = {
    background = false, -- Disable setting the background color
    cursorline = false, -- Disable the cursorline
    eob_lines = true, -- Hide the end-of-buffer lines
  },
  custom_highlights = {
    Normal = { fg = colors.red }
  }, -- Overwrite default highlight groups
})
EOF

colorscheme onenord
```
<img width="1542" alt="Screen Shot 2021-11-08 at 3 53 10 PM" src="https://user-images.githubusercontent.com/52933714/140836607-2d659ce3-bc8e-46eb-a505-477e9d79f0b6.png">

**Comment by rmehri01** [comment]
Do you have any updates on this @jrafaaael?

**Comment by Steven0351** [comment]
I had this same issue with LunarVim and my fix was to do the following instead:
```lua
lvim.colorscheme = nil -- "onenord"
vim.cmd [[colorscheme onenord]]
```
From what I can tell, it seems like LunarVim is loading the colors before the config is applied 🤷‍♂️

**Comment by Steven0351** [comment]
> I think for LunarVim the following works for me, can you try this @Steven0351?
> 
> ```lua
> lvim.colorscheme = "onenord"
> 
> lvim.plugins = {
>   {
>     "rmehri01/onenord.nvim",
>     config = function()
>       -- your config here
>     end,
>   }
> }
> ```

That is what i've been trying, for whatever reason it's keeping the defaults:
```lua
lvim.colorscheme = "onenord"

lvim.plugins = {
    { 
      "rmehri01/onenord.nvim",
      config = function()
        local colors = require"onenord.colors"
        require"onenord".setup({
          custom_highlights = {
            TSNamespace = { fg = colors.dark_blue },
          },
        })
      end
    },
}
```
<img width="382" alt="Screen Shot 2021-11-25 at 11 50 10 AM" src="https://user-images.githubusercontent.com/24440751/143484904-d09869c4-6699-44e6-9877-79b0066834cc.png">

I don't really think it's a problem with onenord since I was able to get it working briefly, though I do appreciate your fast response.

**Comment by rmehri01** [comment]
No problem! Oh I see, yeah in LunarVim when I do `:colorscheme onenord` then it loads the config but when I restart it doesn't keep them. 

Actually this might be a problem with onenord since I tried out a few themes such as [doom-nvim](https://github.com/NTBBloodbath/doom-nvim) and [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) and they seem to both change on config save and preserve the changes when restarting. I'll look into it tonight and hopefully find a fix soon!

**Comment by Steven0351** [comment]
While the root cause is being figured out I found this to be a decent solution to the issue without having to manually toggle colorscheme on each change or startup:
```lua
{
    "rmehri01/onenord.nvim",
    config = function()
      local colors = require("onenord.colors")

      require("onenord").setup({
        custom_highlights = {
          TSNamespace = { fg = colors.purple },
        },
      })

      if lvim.colorscheme == "onenord" then
        vim.cmd [[colorscheme onenord]]
      end
    end
},
```

**Comment by rmehri01** [comment]
Alright I think I fixed the issue, it seemed to be something weird with caching on `require`. Can you confirm that it works regularly for you now @Steven0351?

**Comment by Steven0351** [comment]
> Alright I think I fixed the issue, it seemed to be something weird with caching on `require`. Can you confirm if it works regularly for you now @Steven0351?

Looks to be working as expected for me!

**Comment by rmehri01** [comment]
Alright, I'll close this then. Thanks for testing it out!

**Comment by jrafaaael** [comment]
@rmehri01 Hey! I apologize for the late reply. Still not working for me :(

**Comment by rmehri01** [comment]
Hi, [like I said](https://github.com/rmehri01/onenord.nvim/issues/8#issuecomment-963682240), I can't see where this issue is coming from so do you have a small config I could try?
